fix: player state not being updated to completed
bluefireteam/audioplayers pull request #1257
Opened 2022-08-28 17:03 UTC by itsJoKr

# Description

This is regression introduced in 1.0.0.

In 0.2.0, this logic was:

```dart
      case 'audio.onComplete':
          player.state = PlayerState.COMPLETED;
          player._completionController.add(null);
```

So along with the completionController stream being update, the state was set to completed. 
In 1.0.0 there is no such functionality:

```dart
      case 'audio.onComplete':
        emitComplete(playerId);
```

Since `audioplayers_platform_interface` package doesn't have a reference to `player.state` anymore because it's now in `audioplayers` package, my fix consisted of simply listening to this same stream in `audioplayers` package and updating the state.

## Checklist

- [x] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:`, `chore:` etc).
- [x] I have read the [Contributor Guide] and followed the process outlined for submitting PRs.
- [ ] I have updated/added tests for ALL new/updated/fixed functionality.

I'm not sure how to test this properly.

- [x] I have updated/added relevant documentation and added dartdoc comments with `///`, where necessary.
- [x] I have updated/added relevant examples in [example].

## Breaking Change

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

## Related Issues

https://github.com/bluefireteam/audioplayers/issues/1242

2022-08-29 11:04 UTC, itsJoKr commented on packages/audioplayers_platform_interface/lib/method_channel_audioplayers_platform.dart
> +        emitPlayerState(playerId, PlayerState.completed);
This is not needed for this particular fix, but I left it for discussion. I was quite confused because other streams from the platform interface are being exposed and available for end-developer.

But PlayerState stream, is created from fresh in the main package (audiplayers.dart) and this stream from platform interface is not used anywhere.

2022-08-30 14:31 UTC, Gustl22 commented on packages/audioplayers_platform_interface/lib/method_channel_audioplayers_platform.dart
> +        emitPlayerState(playerId, PlayerState.completed);
Indeed, `emitPlayerState` is not used anywhere. But I would remove it completely from [here](https://github.com/bluefireteam/audioplayers/blob/6fad1cc4443e623e5c94519f130b4004b2dc3857/packages/audioplayers_platform_interface/lib/streams_interface.dart#L52) (maybe in another PR) and call onPlayerState(PlayerState.completed) also in the constructor, when completed event is emitted. @luanpotter what do you think about this? I think `emitPlayerState` is kind of redundant.

2022-08-30 16:05 UTC, Gustl22 commented
Thank you! I also added a `getState` button in upcoming MR #1238 to test this.

2022-09-04 17:25 UTC, itsJoKr commented on packages/audioplayers_platform_interface/lib/method_channel_audioplayers_platform.dart
> +        emitPlayerState(playerId, PlayerState.completed);
I agree that would make it clearer.

2022-09-04 17:26 UTC, itsJoKr commented
I realized I haven't dispose resources properly, so added one more commit.

2022-09-06 12:58 UTC, spydon commented
Formatting fails in the CI, if you just run `flutter format .` it should be fine

2022-09-06 18:02 UTC, Gustl22 commented on packages/audioplayers_platform_interface/lib/method_channel_audioplayers_platform.dart
> +        emitPlayerState(playerId, PlayerState.completed);
@luanpotter any thoughts?

2022-09-08 13:45 UTC, luanpotter commented on packages/audioplayers_platform_interface/lib/method_channel_audioplayers_platform.dart
> +        emitPlayerState(playerId, PlayerState.completed);
isn't it exposed here?
```
  Stream<ForPlayer<PlayerState>> get playerStateStream =>
      _playerStateStreamController.stream;
```
so are you proposing removing this public accessor?

2022-09-09 21:46 UTC, Gustl22 commented on packages/audioplayers_platform_interface/lib/method_channel_audioplayers_platform.dart
> +        emitPlayerState(playerId, PlayerState.completed);
@luanpotter Yes it is exposed, but it never receives any updates / never is called, so basically useless. So the only reason to keep it, would be to propagate, when a stream has started or stopped or released etc. But this is all already done on the dart side, not on the native side.

So currently it does not add any value and is a bit confusing. And I also cannot think of any event, which will be added in the future, which currently cannot be implemented with the other existing events. 

Alternatively we ditch the `emitComplete` in favor of the `emitPlayerState`, but that does not really make sense, if not handling these events on the native side.

2022-09-17 22:55 UTC, Gustl22 commented on packages/audioplayers_platform_interface/lib/method_channel_audioplayers_platform.dart
> +        emitPlayerState(playerId, PlayerState.completed);
@luanpotter I think your opinion is quite important here, as it's a breaking change for the interface. Do you agree on my suggestion? Although the removing of `emitPlayerState` does not have to be part of this PR yet. But the implementation to propagate the `onComplete` event on the dart side would be different.

2022-09-18 20:21 UTC, luanpotter commented on packages/audioplayers_platform_interface/lib/method_channel_audioplayers_platform.dart
> +        emitPlayerState(playerId, PlayerState.completed);
I agree. let's remove it. :shipit: 
thanks for the careful explanation :)

2022-09-19 00:49 UTC, Gustl22 requested changes

2022-09-19 00:49 UTC, Gustl22 commented on packages/audioplayers/lib/src/audioplayer.dart
> +
I would not change the order of the constructor. I know the it's not the recommended order, but we should change it in one go for the whole packe, if it's really important.
```suggestion
```

2022-09-19 00:49 UTC, Gustl22 commented on packages/audioplayers/lib/src/audioplayer.dart
> +  StreamSubscription? _onPlayerCompleteStreamSubscription;
Can't we declare it with `late`. It should always be available, as it's initialized in the constructor.
```suggestion
  late StreamSubscription _onPlayerCompleteStreamSubscription;
```

2022-09-19 00:49 UTC, Gustl22 commented on packages/audioplayers/lib/src/audioplayer.dart
> -
Readd constructor here:

```suggestion
  /// Creates a new instance and assigns an unique id to it.
  AudioPlayer({String? playerId}) : playerId = playerId ?? _uuid.v4() {
    _onPlayerCompleteStreamSubscription = onPlayerComplete.listen((_) {
      state = PlayerState.completed;
    });
  }

```

2022-09-19 00:49 UTC, Gustl22 commented on packages/audioplayers/lib/src/audioplayer.dart
> +
Also no need to check for null, if it's always initialized:

```suggestion
    final futures = <Future>[
      if (!_playerStateController.isClosed) _playerStateController.close(),
      _onPlayerCompleteStreamSubscription.cancel()
    ];

```

2022-09-19 00:49 UTC, Gustl22 commented on packages/audioplayers_platform_interface/lib/method_channel_audioplayers_platform.dart
> +import 'package:audioplayers_platform_interface/api/player_state.dart';
We should remove this again, as player state is already updated in dart implementation. In another MR we can remove all the playerState event stuff from the `audioplayers_interface` as it's not listened and not triggered.

```suggestion
```

2022-09-19 00:49 UTC, Gustl22 commented on packages/audioplayers_platform_interface/lib/method_channel_audioplayers_platform.dart
> +        emitPlayerState(playerId, PlayerState.completed);
Removing, as it's not called or listened to.
```suggestion
```

2022-09-23 14:30 UTC, itsJoKr commented on packages/audioplayers/lib/src/audioplayer.dart
> -
Sorry, I somehow missed this. I see you are adding commits, so should you add this change too?

2022-09-23 15:10 UTC, Gustl22 commented on packages/audioplayers/lib/src/audioplayer.dart
> -
I did all the changes. Hope you agree with them. If not let me know ;D

2022-09-23 15:11 UTC, Gustl22 approved these changes

2022-09-23 15:20 UTC, spydon approved these changes

2022-09-23 15:35 UTC, merged

2022-11-03 14:03 UTC, pooblej commented
Hi,  I am using 

audioplayers:
    git:
      url: https://github.com/itsJoKr/audioplayers.git
      path: packages/audioplayers
      ref: f82378f476dcf5a597ef02ba1ed7294eb3a65f7d

from [itsJoKr] fix for this and I can confirm it works for Android - but does not work for iOS or Web
Is there any change the same fix can be applied to resolve these?

--- Sample ---

    play()
    async { await widget.audioPlayer.play(UrlSource(widget.openingAudio_game01[widget.openAudio]));}
    widget.audioPlayer.play(UrlSource(widget.openingAudio_game01[widget.openAudio]));
    widget.audioPlayer.onPlayerComplete.listen((event){
      print(widget.audioPlayer.state == PlayerState.playing);
      if (widget.openAudio < widget.openingAudio_game01.length)
      {       play();        widget.openAudio = widget.openAudio + 1;      }    }    );  }

2022-11-03 20:09 UTC, Gustl22 commented
@pooblej it should work with latest release also on web. I added tests for it. 
Plz consider opening a separate issue, if still having problems.

2022-11-04 15:26 UTC, pooblej commented
@Gustl22 - I amended to use audioplayers:
git:
url: https://github.com/bluefireteam/audioplayers.git

Android continues to work, but iOS and Web don't. 
Is it anything to do with UrlSource?