chore(release): Publish packages
bluefireteam/audioplayers pull request #1399
Opened 2023-01-24 22:40 UTC by spydon

- audioplayers@3.0.0
 - audioplayers_android@2.0.0
 - audioplayers_darwin@3.0.0
 - audioplayers_linux@1.0.4
 - audioplayers_platform_interface@4.0.0
 - audioplayers_web@2.2.0
 - audioplayers_windows@1.1.3

2023-01-24 23:58 UTC, Gustl22 commented
Hmm I'm not sure about the update interval...we may should introduce a beta channel, so we don't have to bump the main version so frequently.
Besides I'm a big fan of regular updates, but keeping the breaking ones collected.

Also some Changelogs are duplicated, maybe melos messed sth up and compared to the wrong version(?)

2023-01-28 00:55 UTC, Gustl22 commented on CHANGELOG.md
> +
As far as I can tell, some of these changelogs were already in 2.0.0 or even 1.2.0. These duplicated changelogs are throughout all packages. We should remove them and only leave the ones which have actually changed from the previous release.

2023-01-28 00:57 UTC, Gustl22 requested changes
We should remove the duplicated changelogs before merging.

2023-01-28 01:04 UTC, spydon commented on CHANGELOG.md
> +
Wtf, must have been a bug in melos, trying to fix it

2023-01-28 01:07 UTC, Gustl22 commented
> The problem is the maintenance cost that comes with that, since we'd have to have two branches that we cherry-pick back and forth from. But I do agree that we should try to collect breaking changes better than we have. Yesterday I just bumped it so that it would work with Flutter 3.7.0. 

I more thought of leaving the `main` branch as it is, but if there's need for a fast release, we first do a pre-release, that users can use which are dependent on it in that moment, and if it's more settled, we can release it as stable. So we save a few major releases in the stable release then. The users then cannot expect a reliable upgrade in the pre-release without breaking changes (as excpected), but get it earlier.

> There was probably something that accidentally changed within the same PR within that package then.

That was no accident. The flutter action upgraded the Flutter version at around the same time we made the release to be "compatible" with `3.7.0` except that it wasn't tested from our side, and so the lint is breaking.

2023-01-28 01:14 UTC, spydon commented
> I more thought of leaving the `main` branch as it is, but if there's need for a fast release, we first do a pre-release, that users can use which are dependent on it in that moment, and if it's more settled, we can release it as stable. So we save a few major releases in the stable release then. The users then cannot expect a reliable upgrade in the pre-release without breaking changes (as excpected), but get it earlier.

That sounds good!

> That was no accident. The flutter action upgraded the Flutter version at around the same time we made the release to be "compatible" with `3.7.0` except that it wasn't tested from our side, and so the lint is breaking.

I mean that the versioning which is handled by melos picked up that there had been commits with `!` on those packages and therefore marked them as needing a major bump, but I think that was connected to the changelog bug that we just saw.

2023-01-28 01:19 UTC, Gustl22 commented
> I mean that the versioning which is handled by melos picked up that there had been commits with `!` on those packages and therefore marked them as needing a major bump, but I think that was connected to the changelog bug that we just saw.

Ah ok. Yes, I think so, too^^

2023-01-28 01:23 UTC, spydon commented
Can you have a look at the changelogs again @Gustl22? :)
I hope I managed to get rid of the duplicates, but you know better what has been going in since it is almost all your PRs :sweat_smile:

2023-01-28 01:26 UTC, Gustl22 approved these changes

2023-01-28 01:28 UTC, Gustl22 commented
Perfect now! ;D Thank you!

2023-01-28 01:36 UTC, spydon commented
> Perfect now! ;D Thank you!
> 
> Edit: except that mac doesn't like the new flutter version :/ maybe the example app has to be run once on a mac to update the mac specific config files.

Fixed it! It was a discontinued package (path_provider_macos) that was moved (to path_provider_foundation) but we had both in the pubspec.

2023-01-28 09:40 UTC, spydon commented
Baah still something failing, any clue what it could be @Gustl22?

2023-01-28 09:43 UTC, Gustl22 commented
I try to run it on VM later, let's see 😅

2023-01-28 10:53 UTC, spydon commented
> I try to run it on VM later, let's see 😅

Ran the example on my work mac and it seems to work fine, just a few of these in the logs when swapping to the stream tab:
```
2023-01-28 11:47:59.789 audioplayers_example[43120:3881330] Error: Message responses can be sent only once. Ignoring duplicate response on channel 'xyz.luan/audioplayers'.
```

Running the integration tests now, I've never done that locally before, it's quite a sound experience. 😂

2023-01-28 11:35 UTC, spydon commented
Locally the MacOS integration tests passed on Ventura 13.1, which should be the same as the pipeline is running...

2023-01-28 13:18 UTC, spydon commented
Apparently from Flutter 3.7.0 the macos build is by default render with metal, and GitHub CI doesn't support that. :cry:

2023-01-28 13:39 UTC, Gustl22 commented
> Apparently from Flutter 3.7.0 the macos build is by default render with metal, and GitHub CI doesn't support that. :cry: 

Is there already an issue open, and  maybe can we link that inside the code?

2023-01-28 13:49 UTC, spydon commented
> > Apparently from Flutter 3.7.0 the macos build is by default render with metal, and GitHub CI doesn't support that. cry
> 
> Is there already an issue open, and maybe can we link that inside the code / Todo, so we don't loose track?

Added an issue and referenced it in the TODO.

2023-01-28 14:24 UTC, merged

2023-01-28 14:29 UTC, Gustl22 commented
Perfect! Finally getting there ;D

2023-01-28 14:35 UTC, spydon commented
Phew!
I'll do a patch release of MacOS since there was something broken there. :)